[pytest]
addopts =
    --alluredir=allure-results
    -v
    --tb=short

markers =
    smoke: Quick sanity checks
    regression: Full regression suite

filterwarnings =
    ignore::DeprecationWarning
